[package]
name = "wac"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
indexmap = "2.12.1"
serde = "1.0.228"
serde_json = "1.0.146"
serde_with = { version = "3.16.1", features = [ "base64" ] }
wac-graph = "0.8.1"
wac-parser = "0.8.1"
